#!/bin/bash

# Fix dates MongoDB - Utilise ISODate au lieu de string

echo "🔧 Connexion à MongoDB..."
echo ""
echo "Copie-colle ces commandes dans mongosh :"
echo ""
echo "mongosh \"mongodb://mongo:YOUR_PASSWORD@hopper.proxy.rlwy.net:59846\""
echo ""
echo "use premierdelan"
echo ""
echo "# Supprime les champs texte (si ajoutés par erreur)"
echo "db.events.updateOne("
echo "  { \"titre\": \"Réveillon 2026\" },"
echo "  { \$unset: { \"date_ouverture_inscription\": \"\", \"date_fermeture_inscription\": \"\" } }"
echo ")"
echo ""
echo "# Ajoute les champs avec le bon format ISODate"
echo "db.events.updateOne("
echo "  { \"titre\": \"Réveillon 2026\" },"
echo "  { "
echo "    \$set: { "
echo "      \"date_ouverture_inscription\": new Date(\"2025-10-13T10:00:00Z\"),"
echo "      \"date_fermeture_inscription\": new Date(\"2025-12-31T23:59:00Z\")"
echo "    }"
echo "  }"
echo ")"
echo ""
echo "# Vérifie"
echo "db.events.findOne({ \"titre\": \"Réveillon 2026\" })"
echo ""
echo "exit"

